default:
	lessc mask.less mask.css
	lessc index.less index.css
	lessc plan.less plan.css
	lessc about.less about.css
	lessc qa.less qa.css
	lessc req.less req.css
	lessc as.less as.css
	lessc ass.less ass.css
	lessc poll.less poll.css
	lessc rule.less rule.css
	lessc indiv.less indiv.css
	lessc set_password.less set_password.css
	lessc register.less register.css

