default:
	lessc mask.less mask.css
	lessc index.less index.css
	lessc plan.less plan.css
	lessc about.less about.css
	lessc qa.less qa.css
	lessc req.less req.css
	lessc as.less as.css
	lessc poll.less poll.css
	lessc rule.less rule.css
	lessc indiv.less indiv.css

